openapi: 3.0.3
info:
  title: Swagger AWS shop Import Service - OpenAPI 3.0
  description: |-
    Import Service API documentation for the frontend app [React-shop-cloudfront](https://github.com/lobovskiy/nodejs-aws-shop-react).
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://nsr51h1em5.execute-api.eu-central-1.amazonaws.com/dev/
tags:
  - name: import
    description: Shop files import
paths:
  /import:
    get:
      tags:
        - import
      summary: Get signed url to import csv file
      description: Returns a signed url
      operationId: importProductsFile
      parameters:
        - name: 'name'
          in: 'query'
          description: the name of csv file to import
          required: true
          schema:
            type: 'string'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignedUrl'
        '400':
          description: Invalid provided import parameters
        '500':
          description: Internal Server Error, default server error code
components:
  schemas:
    SignedUrl:
      type: string
      description: Signed url to import csv file
